### ISSUE TITLE
NSIS: No warning if no internet connection is available when installing an update on Windows

### ISSUE THREAD

**Issue by tbdalgaard** [NicklasTegner/JustUpdate#1]
Steps to reproduce:

1. Turn internet connection off.
2. Run the update.
3. The tool will run and exit.
4. Go to path of program installation. You should only find an uninstall.exe here.
5. Activate internet connection and try steps 1. through 4.
6. All files are installed as expected.

It would be great if there was a warning telling user that there is no internet connection available. Perhaps there should be a retry and a cancel button.

**Comment by NicklasTegner** [comment]
I am not able to reproduce the issue.
If you can, please provide more information.
If you still have this issue, please reopen this issue.
